name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - run: cd tobtoby_frontend && npm install
      - run: cd tobtoby_frontend && npm run build
      - run: pwd
      - run: ls -al

      - name: Verify build directory
        run: |
          if [ ! -d "./tobtoby_frontend/dist" ]; then
            echo "Build directory does not exist"
            exit 1
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./tobtoby_frontend/dist
